services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: weatherdb
    restart: always
    ports:
      - 5432:${DB_PORT}
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db_data:
